[[redirects]]
  from = "/api/*"
  to = "https://citizens-collectible-examines-former.trycloudflare.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
